import moment from 'moment';
import * as yup from 'yup';

export const columns = [
    {
        header:'Area',
        column: 'area',
        type: 'string',
        filterOption: true,
    },
    {
        header:'Luminaria',
        column: 'luminateLabel',
        type: 'string',
        filterOption: true,
        width:200
    },
    {
        header:'Cantidad',
        column: 'amount',
        type: 'string',
        filterOption: true,
    },
    {
        header:'Encendido',
        column: 'start',
        type: 'time',
        filterOption: true,
    },
    {
        header:'Apagado',
        column: 'end',
        type: 'time',
        filterOption: true,
    },
    {
        header:'Dias de uso',
        column: 'days',
        type: 'string',
        filterOption: true,
    },
    {
        header:'Editar',
        column: 'Edit',
        type: 'icon',
        action: 'Edit',
        colorBtn: 'primary',
        filterOption: false
    },
    {
        header:'Eliminar',
        column: 'Delete',
        type: 'icon',
        action: 'Delete',
        colorBtn: 'error',
        filterOption: false
    },
];

export const row = [
    {
        id: 1,
        area: 'Area1',
        luminateLabel: 'Incandescente 15W',
        luminate: 200,
        amount: '2',
        start: moment('2024-02-23T13:30'),
        end: moment('2024-02-23T13:30'),
        days: '28',
    },
    {
        id: 2,
        area: 'Area2',
        luminateLabel: 'Incandescente 25W',
        luminate: 200,
        amount: '5',
        start: moment('2024-02-23T08:00'),
        end: moment('2024-02-23T16:00'),
        days: '20',
    },
    {
        id: 3,
        area: 'Area3',
        luminateLabel: 'Incandescente 55W',
        luminate: 200,
        amount: '20',
        start: moment('2024-02-23T07:30'),
        end: moment('2024-02-23T17:30'),
        days: '30',
    },
    {
        id: 4,
        area: 'Area4',
        luminateLabel: 'Incandescente 35W',
        luminate: 200,
        amount: '42',
        start: moment('2024-02-23T09:30'),
        end: moment('2024-02-23T22:00'),
        days: '14',
    },
    {
        id: 5,
        area: 'Area2',
        luminateLabel: 'Incandescente 25W',
        luminate: 200,
        amount: '5',
        start: moment('2024-02-23T08:00'),
        end: moment('2024-02-23T16:00'),
        days: '20',
    },
    {
        id: 6,
        area: 'Area3',
        luminateLabel: 'Incandescente 55W',
        luminate: 200,
        amount: '20',
        start: moment('2024-02-23T07:30'),
        end: moment('2024-02-23T17:30'),
        days: '30',
    },
    {
        id: 7,
        area: 'Area4',
        luminateLabel: 'Incandescente 35W',
        luminate: 200,
        amount: '42',
        start: moment('2024-02-23T09:30'),
        end: moment('2024-02-23T22:00'),
        days: '14',
    },
];

export const optionsComponents = {
    showSeachInput: true,
    showAddBtn: true,
    showTable: true,
};

export const typeIluminary = [
    {value: 15, label: 'Incandescente 15W'},
    {value: 25, label: 'Incandescente 25W'},
    {value: 40, label: 'Incandescente 40W'},
    {value: 60, label: 'Incandescente 60W'},
    {value: 75, label: 'Incandescente 75W'},
    {value: 100, label: 'Incandescente 100W'},
    {value: 150, label: 'Incandescente 150W'},
    {value: 200, label: 'Incandescente 200W'},
    {value: 7, label: 'Fluorescente Compacto 7W'},
    {value: 0, label: 'Otro'},
    {value: 9, label: 'Fluorescente Compacto 9W'},
    {value: 13, label: 'Fluorescente Compacto 13W'},
    {value: 15, label: 'Fluorescente Compacto 15W'},
    {value: 18, label: 'Fluorescente Compacto 18W'},
    {value: 26, label: 'Fluorescente Compacto 26W'},
    {value: 32, label: 'Fluorescente Compacto 32W'},
    {value: 17, label: 'Fluorescente Tubular T8 17W'},
    {value: 32, label: 'Fluorescente Tubular T8 32W'},
    {value: 20, label: 'Fluorescente Tubular T12 20W'},
    {value: 40, label: 'Fluorescente Tubular T12 40W'},
    {value: 75, label: 'Fluorescente Tubular T12 75W'},
    {value: 90, label: 'Fluorescente Tubular T12 90W'},
    {value: 22, label: 'Fluorescente Circular 22W'},
    {value: 300, label: 'Halogenas 300W'},
    {value: 500, label: 'Halogenas 500W'},
    {value: 1000, label: 'Halogenas 1000W'},
    {value: 1500, label: 'Fuorescente 1500W'},
    {value: 2000, label: 'Halogenas 2000W'},
    {value: 5, label: 'Led 5W'},
    {value: 6, label: 'Led 6W'},
    {value: 9, label: 'Led 9W'},
    {value: 12, label: 'Led 12W'},
    {value: 13, label: 'Led 13W'},
    {value: 15, label: 'Led 15W'},
    {value: 16, label: 'Led 16W'},
    {value: 18, label: 'Led 18W'},
    {value: 20, label: 'Led 20W'},
    {value: 30, label: 'Led 30W'},
    {value: 45, label: 'Led 45W'},
    {value: 160, label: 'Luz Mixta 160W'},
    {value: 250, label: 'Luz Mixta 250W'},
    {value: 500, label: 'Luz Mixta 500W'},
    {value: 1000, label: 'Luz Mixta 1000W'},
    {value: 80, label: 'Vapor de Mercurio 80W'},
    {value: 100, label: 'Vapor de Mercurio 100W'},
    {value: 125, label: 'Vapor de Mercurio 125W'},
    {value: 175, label: 'Vapor de Mercurio 175W'},
    {value: 250, label: 'Vapor de Mercurio 250W'},
    {value: 400, label: 'Vapor de Mercurio 400W'},
    {value: 1000, label: 'Vapor de Mercurio 1000W'},
    {value: 250, label: 'Metal Halide 250W'},
    {value: 400, label: 'Metal Halide 400W'},
    {value: 1000, label: 'Metal Halide 1000W'},
    {value: 2000, label: 'Metal Halide 2000W'},
    {value: 3500, label: 'Metal Halide 3500W'},
    {value: 50, label: 'Sodio Alta Presion 50W'},
    {value: 70, label: 'Sodio Alta Presion 70W'},
    {value: 100, label: 'Sodio Alta Presion 100W'},
    {value: 150, label: 'Sodio Alta Presion 150W'},
    {value: 250, label: 'Sodio Alta Presion 250W'},
    {value: 400, label: 'Sodio Alta Presion 400W'},
    {value: 1000, label: 'Sodio Alta Presion 1000W'},
    {value: 18, label: 'Sodio Baja Presion 18W'},
    {value: 35, label: 'Sodio Baja Presion 35W'},
    {value: 55, label: 'Sodio Baja Presion 55W'},
    {value: 90, label: 'Sodio Baja Presion 90W'},
    {value: 135, label: 'Sodio Baja Presion 135W'},
    {value: 180, label: 'Sodio Baja Presion 180W'},
];

export const daysOption = [
    {value: 1, label: '1'},
    {value: 2, label: '2'},
    {value: 3, label: '3'},
    {value: 4, label: '4'},
    {value: 5, label: '5'},
    {value: 6, label: '6'},
    {value: 7, label: '7'},
    {value: 8, label: '8'},
    {value: 9, label: '9'},
    {value: 10, label: '10'},
    {value: 11, label: '11'},
    {value: 12, label: '12'},
    {value: 13, label: '13'},
    {value: 14, label: '14'},
    {value: 15, label: '15'},
    {value: 16, label: '16'},
    {value: 17, label: '17'},
    {value: 18, label: '18'},
    {value: 19, label: '19'},
    {value: 20, label: '20'},
    {value: 21, label: '21'},
    {value: 22, label: '22'},
    {value: 23, label: '23'},
    {value: 24, label: '24'},
    {value: 25, label: '25'},
    {value: 26, label: '26'},
    {value: 27, label: '27'},
    {value: 28, label: '28'},
    {value: 29, label: '29'},
    {value: 30, label: '30'},
    {value: 31, label: '31'},
];


export const bodySend = {    
    area: '',
    luminate: '',
    amount: '',
    start: moment('2024-02-23T00:00'),
    end: moment('2024-02-23T00:00'),
    days: '',
};

export const validationSchema = yup.object({
    area: yup.string().required('El campo es requerido'),
    luminate: yup.number().required('El campo es requerido'),
    amount: yup.string().required('El campo es requerido'),
    start: yup.string().required('El campo es requerido'),
    end: yup.string().required('El campo es requerido'),
    days: yup.number().required('El campo es requerido')
});

export const dataForm =[
    {
        label: 'Area',
        type: 'text',
        name: 'area',
        value: '',
    },
    {
        label: 'Tipo de luminaria',
        type: 'select',
        name: 'luminate',
        value: '',
        dataOption: typeIluminary
    },
    {
        label: 'Cantidad',
        type: 'number',
        name: 'amount',
        value: '',
    },
    {
        label: 'Encendido',
        type: 'time',
        name: 'start',
        value: '',
    },
    {
        label: 'Apagado',
        type: 'time',
        name: 'end',
        value: '',
    },
    {
        label: 'Dias de uso',
        type: 'select',
        name: 'days',
        value: '',
        dataOption: daysOption
    }
];