export const columns = [
    {
        header:'Auditor',
        column: 'auditor',
        type: 'string',
        filterOption: true,
        width:200
    },
    {
        header:'Edificación',
        column: 'edificate',
        type: 'string',
        filterOption: true,
        width:200
    },
    {
        header:'Direccion',
        column: 'adress',
        type: 'string',
        filterOption: true,
        width:200
    },
    {
        header:'Fecha',
        column: 'date',
        type: 'date',
        filterOption: false,
        // width:200
    },
    {
        header:'Editar',
        column: 'Edit',
        type: 'icon',
        action: 'Edit',
        colorBtn: 'primary',
        filterOption: false
    },
    {
        header:'Eliminar',
        column: 'Delete',
        type: 'icon',
        action: 'Delete',
        colorBtn: 'error',
        filterOption: false
    },
];

export const row = [
    {
        auditor: 'Auditor',
        edificate: 'Casa',
        adress: 'Dirección',
        date: '15/02/24',
    },
    {
        auditor: 'Auditor2',
        edificate: 'Casa',
        adress: 'Centro',
        date: '15/02/24',
    },
    {
        auditor: 'Auditor4',
        edificate: 'Terreno',
        adress: 'Oeste',
        date: '15/02/24',
    },
];

export const optionsComponents = {
    showSeachInput: true,
    showAddBtn: true,
    showTable: true,
}

export const typeIluminary = [
    {value: 15, label: 'Incandescente 15W'},
    {value: 25, label: 'Incandescente 25W'},
    {value: 40, label: 'Incandescente 40W'},
    {value: 60, label: 'Incandescente 60W'},
    {value: 75, label: 'Incandescente 75W'},
    {value: 100, label: 'Incandescente 100W'},
    {value: 150, label: 'Incandescente 150W'},
    {value: 200, label: 'Incandescente 200W'},
    {value: 7, label: 'Fluorescente Compacto 7W'},
    {value: 0, label: 'Otro'},
    {value: 9, label: 'Fluorescente Compacto 9W'},
    {value: 13, label: 'Fluorescente Compacto 13W'},
    {value: 15, label: 'Fluorescente Compacto 15W'},
    {value: 18, label: 'Fluorescente Compacto 18W'},
    {value: 26, label: 'Fluorescente Compacto 26W'},
    {value: 32, label: 'Fluorescente Compacto 32W'},
    {value: 17, label: 'Fluorescente Tubular T8 17W'},
    {value: 32, label: 'Fluorescente Tubular T8 32W'},
    {value: 20, label: 'Fluorescente Tubular T12 20W'},
    {value: 40, label: 'Fluorescente Tubular T12 40W'},
    {value: 75, label: 'Fluorescente Tubular T12 75W'},
    {value: 90, label: 'Fluorescente Tubular T12 90W'},
    {value: 22, label: 'Fluorescente Circular 22W'},
    {value: 300, label: 'Halogenas 300W'},
    {value: 500, label: 'Halogenas 500W'},
    {value: 1000, label: 'Halogenas 1000W'},
    {value: 1500, label: 'Fuorescente 1500W'},
    {value: 2000, label: 'Halogenas 2000W'},
    {value: 5, label: 'Led 5W'},
    {value: 6, label: 'Led 6W'},
    {value: 9, label: 'Led 9W'},
    {value: 12, label: 'Led 12W'},
    {value: 13, label: 'Led 13W'},
    {value: 15, label: 'Led 15W'},
    {value: 16, label: 'Led 16W'},
    {value: 18, label: 'Led 18W'},
    {value: 20, label: 'Led 20W'},
    {value: 30, label: 'Led 30W'},
    {value: 45, label: 'Led 45W'},
    {value: 160, label: 'Luz Mixta 160W'},
    {value: 250, label: 'Luz Mixta 250W'},
    {value: 500, label: 'Luz Mixta 500W'},
    {value: 1000, label: 'Luz Mixta 1000W'},
    {value: 80, label: 'Vapor de Mercurio 80W'},
    {value: 100, label: 'Vapor de Mercurio 100W'},
    {value: 125, label: 'Vapor de Mercurio 125W'},
    {value: 175, label: 'Vapor de Mercurio 175W'},
    {value: 250, label: 'Vapor de Mercurio 250W'},
    {value: 400, label: 'Vapor de Mercurio 400W'},
    {value: 1000, label: 'Vapor de Mercurio 1000W'},
    {value: 250, label: 'Metal Halide 250W'},
    {value: 400, label: 'Metal Halide 400W'},
    {value: 1000, label: 'Metal Halide 1000W'},
    {value: 2000, label: 'Metal Halide 2000W'},
    {value: 3500, label: 'Metal Halide 3500W'},
    {value: 50, label: 'Sodio Alta Presion 50W'},
    {value: 70, label: 'Sodio Alta Presion 70W'},
    {value: 100, label: 'Sodio Alta Presion 100W'},
    {value: 150, label: 'Sodio Alta Presion 150W'},
    {value: 250, label: 'Sodio Alta Presion 250W'},
    {value: 400, label: 'Sodio Alta Presion 400W'},
    {value: 1000, label: 'Sodio Alta Presion 1000W'},
    {value: 18, label: 'Sodio Baja Presion 18W'},
    {value: 35, label: 'Sodio Baja Presion 35W'},
    {value: 55, label: 'Sodio Baja Presion 55W'},
    {value: 90, label: 'Sodio Baja Presion 90W'},
    {value: 135, label: 'Sodio Baja Presion 135W'},
    {value: 180, label: 'Sodio Baja Presion 180W'},
]
